### ISSUE TITLE
[Bug] can't reforged Mythic Metals armor on mod TieredZ

### ISSUE THREAD

**Issue by himansure** [Noaaan/MythicMetals#260]
I can't Reforged armor Mythic Metal (other mod work correctly) in mod TieredZ
Video:

https://github.com/user-attachments/assets/bf1c1426-6eed-4092-a568-6b63605a64ab

**Comment by Noaaan** [comment]
I highly doubt this is an issue with Mythic Metals itself. It is more likely an issue with TieredZ itself, or something else (maybe your modpack has changed what gear you can reforge?)

**Comment by himansure** [comment]
I sent you a logs?

https://pastebin.com/mTwqHK23

**Comment by Noaaan** [comment]
Closing this as it is the same issue as #263. It should already be fixed with the next release of 1.21. I generally don't do backports for 1.20, but this should be fixable from a modpack standpoint with a simple datapack that bundles the armor tags found here: https://github.com/Noaaan/MythicMetals/tree/1.21/src/main/generated/data/minecraft/tags/item

**Comment by himansure** [comment]
Thanks for new 1.21 version, but I still don't understand how to fix it
because my mod is in version 1.20.1

Vào Th 2, 30 thg 9, 2024 vào lúc 00:08 Noaaan ***@***.***>
đã viết:
