### ISSUE TITLE
[1.21.4 alpha] Loot Tables not working

### ISSUE THREAD

**Issue by etwerpthegreat** [Noaaan/MythicMetals#307]
Ever since I downloaded the new alpha file for 1.21.4, the ores (like orichalcum, adamantite, even the worse-tier ones) are no longer dropping anything. **_They give me XP and I am using the right tools, but I never get any ore,_** which as you can guess, certainly won't work in the long run. If you do see this, please look into it thanks sm. also this mod is amazing thank you.

**Comment by Noaaan** [comment]
I'll take a look at it as soon as I am able to. Not sure if I will be able to make another alpha release before new years eve

**Comment by Noaaan** [comment]
This should now be fixed, and `0.25.0-alpha.2` should now be available. Do let me know if you find any more issues with this alpha release

**Comment by etwerpthegreat** [comment]
Thank you for responding so fast. Unfortunately it does seem like the ore still isn't dropping anything. I'm going to test a couple things on my end like maybe another mod is messing it up and I'll let you know. Since you went through the trouble to respond so quick about my previous request, you don't have to respond too quickly about this one. Thank you!

**Comment by etwerpthegreat** [comment]
> Thank you for responding so fast. Unfortunately it does seem like the ore still isn't dropping anything. I'm going to test a couple things on my end like maybe another mod is messing it up and I'll let you know. Since you went through the trouble to respond so quick about my previous request, you don't have to respond too quickly about this one. Thank you!

Just as a P.S. to this i ran a world with only Mythic Metals and all the things that it requires to run (fabric api, owolib, alloy forgery) and it still wasn't dropping anything, so that confirms there was no connection issue with another mod. Not sure if this helps but I thought I'd share.

**Comment by Noaaan** [comment]
I definitely fixed it. I think I accidentally uploaded an older version without the fix. Should be trivial to re-release. I'll have alpha 3 up in a minute

**Comment by etwerpthegreat** [comment]
Sweet thanks sm man

**Comment by etwerpthegreat** [comment]
Thank you so much it works now. I really appreciate you getting back to me so fast. Happy New Years man!
